Repository conda/conda-recipe-manager, pull requests merged in 2024-10, with the labels that each got.

#179 Minor Updates to Issue Templates
  .github/ISSUE_TEMPLATE/01_bug-report.md
  .github/ISSUE_TEMPLATE/02_feature-request.md
  .github/ISSUE_TEMPLATE/03_project-owner-feature.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: cla-signed

#106 add patch command
  conda_recipe_manager/commands/conda_recipe_manager.py
  conda_recipe_manager/commands/patch.py
  conda_recipe_manager/commands/utils/types.py
  tests/commands/test_patch.py
  tests/test_aux_files/patch/bad_json_patch_files/bad_json_patch.json
  tests/test_aux_files/patch/bad_json_patch_files/empty_json.json
  tests/test_aux_files/patch/bad_recipe_files/missing_colon.yaml
  tests/test_aux_files/patch/bad_recipe_files/missing_key.yaml
  tests/test_aux_files/patch/json_patch.json
  tests/test_aux_files/patch/single_patch.json
Labels: cla-signed

#176 Update `convert` to properly handle complex Jinja expressions
  conda_recipe_manager/parser/_types.py
  conda_recipe_manager/parser/recipe_parser_convert.py
  tests/parser/test_recipe_parser_convert.py
  tests/test_aux_files/regression_jinja_sub.yaml
  tests/test_aux_files/v1_format/v1_regression_jinja_sub.yaml
Labels: bug, cla-signed

#191 Fixes #186: Parser cannot handle addition in JINJA replacements
  conda_recipe_manager/parser/_types.py
  conda_recipe_manager/parser/recipe_reader.py
  tests/parser/test_recipe_reader.py
  tests/test_aux_files/sub_vars.yaml
  tests/test_aux_files/v1_format/v1_sub_vars.yaml
Labels: cla-signed

#180 Python code Dependency Scanner Prototype
  .pytest.ini
  conda_recipe_manager/parser/cbc_parser.py
  conda_recipe_manager/scanner/dependency/__init__.py
  conda_recipe_manager/scanner/dependency/base_dep_scanner.py
  conda_recipe_manager/scanner/dependency/py_dep_scanner.py
  conda_recipe_manager/types.py
  recipe/meta.yaml
  tests/scanner/dependency/test_py_dep_scanner.py
  tests/test_aux_files/software_projects/dummy_py_project_01/src/__init__.py
  tests/test_aux_files/software_projects/dummy_py_project_01/src/dummy_module.py
  tests/test_aux_files/software_projects/dummy_py_project_01/src/main.py
  tests/test_aux_files/software_projects/dummy_py_project_01/tests/test_dummy_py_main.py
Labels: cla-signed

#192 Add `__init__.py` files to all test directories
  tests/commands/__init__.py
  tests/fetcher/__init__.py
  tests/grapher/__init__.py
  tests/license/__init__.py
  tests/parser/__init__.py
  tests/scanner/dependency/__init__.py
  tests/test_aux_files/software_projects/dummy_py_project_01/tests/__init__.py
  tests/utils/__init__.py
  tests/utils/cryptography/__init__.py
Labels: testing, cla-signed

#193 v0.3.0 commit
  CHANGELOG.md
  README.md
  docs/conf.py
  pyproject.toml
Labels: cla-signed

#194 Forgot to include some minor changes in the v0.3.0 release commit
  README.md
  recipe/meta.yaml
Labels: cla-signed

#195 Updates the recipe doc link
  recipe/meta.yaml
Labels: cla-signed

#199 Fixes #197 and adds regression tests. Also fixes #190
  conda_recipe_manager/parser/_utils.py
  conda_recipe_manager/parser/recipe_reader.py
  tests/parser/test_recipe_parser_convert.py
  tests/parser/test_recipe_reader.py
  tests/test_aux_files/sub_vars.yaml
  tests/test_aux_files/v1_format/v1_sub_vars.yaml
Labels: cla-signed

#200 Removes missed debug statement
  conda_recipe_manager/parser/recipe_reader.py
Labels: cla-signed

#204 Removes conda-forge channel
  .pre-commit-config.yaml
  environment.yaml
Labels: cla-signed

#196 Test the `MessageTable` class
  tests/test_types.py
Labels: testing, cla-signed

#209 207 Refactor `RecipeParserDeps`
  conda_recipe_manager/grapher/recipe_graph.py
  conda_recipe_manager/grapher/recipe_graph_from_disk.py
  conda_recipe_manager/parser/dependency.py
  conda_recipe_manager/parser/recipe_parser.py
  conda_recipe_manager/parser/recipe_parser_deps.py
  conda_recipe_manager/parser/recipe_reader_deps.py
  conda_recipe_manager/parser/selector_parser.py
  tests/file_loading.py
  tests/parser/test_pickle_integration.py
  tests/parser/test_recipe_parser.py
  tests/parser/test_recipe_parser_deps.py
  tests/parser/test_recipe_reader_deps.py
  tests/parser/test_selector_parser.py
Labels: bug, enhancement, cla-signed

#210 v0.3.2
  CHANGELOG.md
  docs/conf.py
  pyproject.toml
  recipe/meta.yaml
Labels: cla-signed

#214 Fixes `numpy {{numpy}}` dependency bug
  conda_recipe_manager/parser/dependency.py
  conda_recipe_manager/parser/recipe_parser_deps.py
  conda_recipe_manager/parser/recipe_reader_deps.py
  tests/parser/test_dependency.py
  tests/parser/test_recipe_parser_deps.py
  tests/parser/test_recipe_reader.py
  tests/test_aux_files/h5py.yaml
Labels: cla-signed

#216 v0.3.3
  CHANGELOG.md
  docs/conf.py
  pyproject.toml
  recipe/meta.yaml
Labels: cla-signed

#217 v0.3.4
  CHANGELOG.md
  conda_recipe_manager/parser/dependency.py
  docs/conf.py
  pyproject.toml
  recipe/meta.yaml
Labels: cla-signed

#223 Improves pytest config filter to be less aggressive
  .pytest.ini
Labels: cla-signed
